#!/bin/bash
set -e

mkdir -p $HOME/.openrefine
mkdir -p $HOME/openrefine

mkdir -p $HOME/.jupyter/

OR_VERSION=3.5.2

wget -q -O openrefine-${OR_VERSION}.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/${OR_VERSION}/openrefine-linux-${OR_VERSION}.tar.gz

tar xzf openrefine-${OR_VERSION}.tar.gz -C $HOME/.openrefine
rm openrefine-${OR_VERSION}.tar.gz



#Although located in binder/,
# this bash file runs in $HOME rather than $HOME/binder
mv jupyter_notebook_config.py $HOME/.jupyter/
