#!/bin/bash
set -e

mkdir -p $HOME/.openrefine
mkdir -p $HOME/openrefine

mkdir -p $HOME/.jupyter/

wget -q -O openrefine-3.3.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/3.3/openrefine-linux-3.3.tar.gz

tar xzf openrefine-3.3.tar.gz -C $HOME/.openrefine
rm openrefine-3.3.tar.gz



#Although located in binder/,
# this bash file runs in $HOME rather than $HOME/binder
mv jupyter_notebook_config.py $HOME/.jupyter/